# Generated by Django 4.2.7 on 2023-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers_id', models.CharField(max_length=32, unique=True)),
                ('workers_name', models.CharField(max_length=32)),
            ],
        ),
    ]
