# Generated by Django 3.0.6 on 2023-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_no', models.CharField(max_length=32, unique=True)),
                ('worker_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
