# Generated by Django 3.0.6 on 2023-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_auto_20231205_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=32, unique=True)),
                ('task_owner', models.CharField(max_length=32)),
            ],
        ),
    ]
