# Generated by Django 3.0.6 on 2023-12-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_no', models.CharField(max_length=32, unique=True)),
                ('administrator_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(max_length=32, unique=True)),
                ('group_information', models.CharField(max_length=32)),
                ('group_leader', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_owner',
            new_name='task_information',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_leader',
            field=models.CharField(default=20211190016, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_create',
            field=models.CharField(default=221155, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_password',
            field=models.CharField(default=123456, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_rank',
            field=models.CharField(default=123456, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_sex',
            field=models.CharField(default=123466, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkerToTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Tasks')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Worker')),
            ],
            options={
                'unique_together': {('worker', 'task')},
            },
        ),
        migrations.CreateModel(
            name='WorkerToGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Group')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Worker')),
            ],
            options={
                'unique_together': {('worker', 'group')},
            },
        ),
    ]
