# Generated by Django 3.0.6 on 2023-12-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_auto_20231206_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='worker_create',
            new_name='worker_create_date',
        ),
    ]
