# Generated by Django 3.0.6 on 2023-12-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_auto_20231206_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
