# Generated by Django 3.0.6 on 2023-12-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_auto_20231206_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertogroups',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Group', to_field='group_no'),
        ),
        migrations.AlterField(
            model_name='workertogroups',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Worker', to_field='worker_no'),
        ),
        migrations.AlterUniqueTogether(
            name='workertogroups',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workertotasks',
            unique_together=set(),
        ),
    ]
