# Generated by Django 3.0.6 on 2023-12-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_auto_20231209_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertotasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Task', to_field='task_no'),
        ),
        migrations.AlterField(
            model_name='workertotasks',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Worker', to_field='worker_no'),
        ),
    ]
